kind: Service
apiVersion: v1
metadata:
  name: model-serving
spec:
  selector:
    app: model
    version: 1.0.0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer